version: "3.9"
# Which Compose file syntax to use (controls available features).

services:
  # Start the list of services (containers) you want Docker Compose to manage).

  app:
    # The logical name of this service. Used by docker-compose and internal networking.

    container_name: typescript-app
    # The actual Docker container name. Helpful for manual docker commands,

    ports:
      # Begin a list of published port mappings. Maps host ports → container ports.

      - "4000:4000"
      # Host port 4000 is forwarded to port 4000 inside the container.
      # Access your app at http://localhost:4000 on the host machine.

    env_file:
      # Begin a list of files whose KEY=VALUE lines become environment variables
      # inside the container.

      - ./.env
      # Use the .env file in the same folder as this compose file.
      # Each line must be like: MY_VAR=value. Don’t store secrets in version control.

  mongo:
    # A second service named "mongo" to run a MongoDB database.
    image: mongo
    # Use the official "mongo" image from Docker Hub.

    restart: always
    # Always restart the container if it stops (unless explicitly stopped).

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
